management:
  endpoints:
    web:
      exposure:
        include:
          - gateway
          - metrics
spring:
  cloud:
    gateway:
      globalcors:
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: rpgtracker-core-route
          uri: http://rpgtracker-core:8081
          predicates:
            - Path=/core/**
        - id: rpgtracker-coc-route
          uri: http://rpgtracker-coc:8082
          predicates:
            - Path=/coc/**